/* Extra photo lessons — only stills that exist in the repo. */
(function () {
  window.WRAP911_BOOST = 1;
  if (!window.WRAP911_DATA) window.WRAP911_DATA = {};
  var d = window.WRAP911_DATA;
  if (!d.photoLessons) d.photoLessons = [];

  var extra = [
    { id:"pb-caddy-3", title:"Pink caddy — side hang in the bay", image:"media/videos/fleet/pink-caddy-wrap3.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Dusty-rose Cadillac in the bay mid-wrap.",
      narration:"This is the fleet side hang. Glass the flats, watch the character line, do not chase heat numbers. TDS only.",
      checklist:["Glass the door flats first","Keep the character line level","Heat only to the film TDS","Walk the panel in raking light"],
      quiz:{q:"First move on a fleet side hang?",correct:"Glass the flats and read the character line.",wrong:"Torch the whole door before the film is placed."} },
    { id:"pb-caddy-4", title:"Pink caddy — bumper to fender seam", image:"media/videos/fleet/pink-caddy-wrap4.jpg", module:"seams-rivets", jobType:"Fleet",
      visual:"Seam at bumper-to-fender on the rose wrap.",
      narration:"Seams fail when you stretch across a gap. Overlap to the TDS, seat both faces, post-heat the join.",
      checklist:["Do not stretch across the gap","Overlap per TDS","Seat both faces","Post-heat the join"],
      quiz:{q:"How do you treat a bumper-to-fender seam?",correct:"Overlap per TDS and seat both faces.",wrong:"Pull one panel tight across the gap so there is no seam."} },
    { id:"pb-caddy-5", title:"Pink caddy — rear quarter finish", image:"media/videos/fleet/pink-caddy-wrap5.jpg", module:"post-heat", jobType:"Fleet",
      visual:"Rear quarter after the hang.",
      narration:"Finish is post-heat and edge check. If an edge ticks up, lift, reclean, reseat. Do not glue dirt in.",
      checklist:["Post-heat per TDS","Check wheel-well lips","Reseat any tick-up","Raking light before you call it done"],
      quiz:{q:"Edge ticked up after post-heat. Move?",correct:"Lift, reclean, reseat.",wrong:"Melt it down with a long torch hold."} },
    { id:"pb-caddy-1", title:"Pink wrap caddy — first hang", image:"media/videos/fleet/pink-wrap-caddy-1.jpg", module:"prep", jobType:"Fleet",
      visual:"First film on the caddy.",
      narration:"Prep decides this job. Clay or wipe per shop process, IPA, dry, then hang. Dirty paint becomes a lift line.",
      checklist:["Wash and decon","IPA, then dry","Hang only on a clean panel","Bag dirty towels"],
      quiz:{q:"When does film go on?",correct:"After the panel is clean and dry.",wrong:"As soon as the roll is on the floor."} },
    { id:"pb-cherokee", title:"Satin Cherokee — full-side read", image:"media/videos/fleet/satin-wrap-cherokee.jpg", module:"film-types", jobType:"Fleet",
      visual:"Satin SUV side in the bay.",
      narration:"Satin shows squeegee tracks and overstretch more than gloss. Light strokes. Do not burnish satin like gloss.",
      checklist:["Light squeegee pressure","Watch satin marring","No dry burnish","Read the side in raking light"],
      quiz:{q:"Why go light on satin?",correct:"Satin shows tracks and stretch marks that gloss hides.",wrong:"Satin needs more heat than gloss to look even."} },
    { id:"pb-graphic", title:"Printed panel on the bench", image:"media/videos/fleet/graphic-installation-1.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Shop bench. White gloss sheet with a black printed panel and color cards along the top. Hands work the left edge.",
      narration:"This is the bench step for a printed panel. Keep the sheet flat so the print does not crease. Square it here before it ever hits a vehicle. Lift fingers; do not smash them into the art.",
      checklist:["Keep the print flat on the bench","Square the panel before the hang","Lift fingers; do not smash","Watch seams in the art"],
      quiz:{q:"Finger in printed film on the bench. Move?",correct:"Lift and reset tension. Do not smash it flat.",wrong:"Hard squeegee so the print compresses."} },
    { id:"pb-wall", title:"Interior wall wrap", image:"media/videos/architectural/architectural-wall-wrap.jpg", module:"architectural", jobType:"Interior",
      visual:"Wall panel in the shop.",
      narration:"Same film rules as a van. Layout first, hang plumb, squeegee in sequence. Heat only to TDS for fingers.",
      checklist:["Layout and plumb","Sequence the squeegee","Heat fingers to TDS","Trim off the show face"],
      quiz:{q:"What is first on an interior wall?",correct:"Layout and plumb, then hang.",wrong:"Heat the whole wall so the film gets soft."} },
    { id:"pb-wall-sq", title:"Wall squeegee sequence", image:"media/videos/architectural/architectural-wall-wrap-squeegee-sequence.jpg", module:"squeegee", jobType:"Interior",
      visual:"Squeegee pattern on a wall panel.",
      narration:"Sequence beats force. Overlap strokes. Do not leave a dry island in the middle of the panel.",
      checklist:["Overlap strokes","No dry islands","Soft edge on texture","Check raking light"],
      quiz:{q:"Squeegee rule on a wall?",correct:"Overlapped sequence. No dry islands.",wrong:"One hard pass down the center."} },
    { id:"pb-cut-ex1", title:"Cut excess after the wall is down", image:"media/videos/architectural/architectural-panel-cutting-excess-vinyl-after-install-1.jpg", module:"cutting", jobType:"Interior",
      visual:"Trimming excess after install.",
      narration:"Finish cuts use a fresh blade and light pressure. Film only. Do not score the wall.",
      checklist:["Fresh blade","Light pass","Film only","Bag the scrap"],
      quiz:{q:"Finish trim pressure?",correct:"Light. Film only. Fresh blade.",wrong:"Lean on the knife so it does not skip."} },
    { id:"pb-cab-done", title:"Cabinet wrap — faces done", image:"media/videos/architectural/cabinet-done.jpg", module:"architectural", jobType:"Interior",
      visual:"Finished cabinet faces.",
      narration:"Cabinet jobs die at edges and inside corners. Half-moon relief, seat one face, then the other.",
      checklist:["Measure twice","Relief inside corners","Seat one face at a time","No bridging of the door gap"],
      quiz:{q:"Inside cabinet corner. Cut?",correct:"Half-moon relief, then one face at a time.",wrong:"One panel stretched around the box."} },
    { id:"pb-cab-on", title:"Vinyl on cabinet", image:"media/videos/architectural/vinyl-oncabinet8.jpg", module:"architectural", jobType:"Interior",
      visual:"Film on a cabinet box.",
      narration:"Hinge side last. Do not wrap the hinge barrel unless the spec says so. Clean the edge after trim.",
      checklist:["Hinge side last","Do not wrap the barrel unless specked","Clean the cut edge","Check door close"],
      quiz:{q:"When do you wrap the hinge side?",correct:"Last, and only as far as the spec.",wrong:"First, so the door can close on fresh film."} },
    { id:"pb-office", title:"Office wall finish", image:"media/photos/gallery/office-wallpaper-wrap.jpg", module:"architectural", jobType:"Interior",
      visual:"Conference wall wrap.",
      narration:"Architectural film still needs prep. Dust on a wall becomes a tent you will see under lights.",
      checklist:["Dust the wall","Layout seams off sight lines","Squeegee sequence","Raking light at the end"],
      quiz:{q:"Main enemy on an office wall?",correct:"Dust and a seam in the sight line.",wrong:"Not enough torch heat on the field."} },
    { id:"pb-bleed", title:"Measure bleed on wood-grain", image:"media/photos/gallery/measuring-bleed2.jpg", module:"cutting", jobType:"Interior",
      visual:"Measuring bleed on wood-grain film.",
      narration:"Bleed is planned. Cut short and the core shows. Leave wrap allowance, then finish-trim.",
      checklist:["Measure the box","Add bleed","Cut long, trim after hang","Match grain direction"],
      quiz:{q:"Why add bleed?",correct:"So the finish trim does not show the substrate.",wrong:"So you can stretch the grain farther."} },
    { id:"pb-cab-side", title:"Cabinet interior side", image:"media/photos/gallery/cabinet-pic-sides.jpg", module:"architectural", jobType:"Interior",
      visual:"Cabinet interior side and glass corner.",
      narration:"Interior sides are tight. Dry-fit, hinge clearance, then hang. Do not bridge the glass channel.",
      checklist:["Dry-fit the piece","Watch hinge clearance","No bridge on glass channel","Soft squeegee"],
      quiz:{q:"Glass channel next to film. Move?",correct:"Trim to the channel. Do not bridge it.",wrong:"Stretch film over the glass so it looks sealed."} },
    { id:"pb-cab-measure", title:"Cabinet measure before the cut", image:"media/photos/gallery/cabinet-measure.jpg", module:"prep", jobType:"Interior",
      visual:"Measuring cabinet box height.",
      narration:"The cut is only as good as the measure. Height, width, depth, then bleed. Write it on the liner.",
      checklist:["Height, width, depth","Add bleed","Write sizes on the liner","Cut once"],
      quiz:{q:"What do you write on the liner?",correct:"The measured size plus bleed.",wrong:"Only the brand name."} },
    { id:"pb-kiosk", title:"Kiosk box — multi-panel face", image:"media/photos/gallery/kiosk-box.jpg", module:"architectural", jobType:"Interior",
      visual:"Kiosk with cutouts.",
      narration:"Cutouts first in the layout. Relief around openings. Do not stretch art across a hole.",
      checklist:["Mark every cutout","Relief around openings","Keep art square","Trim after the face is glassed"],
      quiz:{q:"Printed kiosk with a hole. Rule?",correct:"Layout the hole first. Do not stretch art across it.",wrong:"Stretch the print over the hole and cut later."} },
    { id:"pb-spot", title:"Trailer nose panel still under tape", image:"media/photos/gallery/trailer-spot-graphics.jpg", module:"post-heat", jobType:"Trailer",
      visual:"Black trailer nose. Printed panel still under grey transfer tape with orange hinge tabs. White side graphic already down.",
      narration:"Nose panel is still taped — dry-fit, not finished. Register it, squeegee, then pull tape low and slow. Trim edges after the tape is gone.",
      checklist:["Register the nose panel under tape","Squeegee the panel","Pull tape low and slow","Trim edges after tape is off"],
      quiz:{q:"When do you trim the taped nose panel?",correct:"After the transfer tape is off.",wrong:"Before you pull tape, so the hinge is free."} },
    { id:"pb-gate", title:"Work van — rear gate wrap", image:"media/videos/van/rear-vehicle-gate-wrap.jpg", module:"squeegee", jobType:"Work van",
      visual:"Rear gate mid-wrap.",
      narration:"Gates have recesses and badges. Glass the flat, relief the handle, do not bridge the latch pocket.",
      checklist:["Glass the gate flat","Relief the handle","No bridge on the latch","Check the close"],
      quiz:{q:"Latch pocket. Move?",correct:"Relief and feed. Do not bridge.",wrong:"Stretch film over the latch so it stays glossy."} },
    { id:"pb-squeegee", title:"Squeegee on the printed sheet", image:"media/videos/prep/squeegee-strokes.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Bench job. Blue sleeve, white squeegee with a green felt edge on a white gloss sheet. Black printed panel and color cards toward the top. Peach in the foreground.",
      narration:"Stroke pattern on the table is the same on the vehicle. Overlap. Soft felt edge. No dry islands. Keep the print flat so type does not kink. The fruit in the foreground is not the job.",
      checklist:["Overlap strokes","Soft felt edge","No dry islands","Wipe the squeegee face","Keep the print flat"],
      quiz:{q:"Why wipe the squeegee?",correct:"Grit on the blade scratches film.",wrong:"So the heat transfers better."} },
    { id:"pb-torch", title:"Heat on vinyl — keep it moving", image:"media/videos/prep/torch-on-vinyl1.jpg", module:"heat", jobType:"Fleet",
      visual:"Torch over film.",
      narration:"Heat is a tool. Keep it moving. TDS only. If the film goes shiny-melted you went past the window.",
      checklist:["Keep the heat moving","TDS only","Stop when pliable","Never hold on one spot"],
      quiz:{q:"Film looks shiny-melted. Meaning?",correct:"You passed the TDS window. Stop.",wrong:"It is ready for a harder squeegee."} },
    /* 2.6.6: was media/videos/prep/vinyl-removal.jpg (a social-media screenshot). Real trailer job still; id kept. */
    { id:"pb-removal", title:"Donut trailer side, liner flaps over the top", image:"media/photos/gallery/donuts-trailer-side-graphic-hang-stage.jpg", module:"squeegee", jobType:"Vehicles",
      visual:"The side of a trailer with a pink printed donut graphic, big white outlined letters, and orange and gold circles. The panels are up, but grey liner and transfer flaps are folded over the top edge, and gold and pink tape strips hang down between the panels. The upper side of the trailer is still white. Two wheels and a silver fender show at the bottom.",
      narration:"This is a trailer side mid-hang. The printed panels are up, but the liner and tape at the top are still on. Those flaps are the hinge, so the panels are not finished.\n\nCheck that the print lines up across each seam before you pull the rest of the liner. Then squeegee each panel down from the hinge and pull the tape low and slow. Trim the top edge last.",
      checklist:["Check the print lines up across each seam","Treat the top flaps as the hinge","Squeegee down from the hinge","Pull tape low and slow","Trim the top edge last"],
      quiz:{q:"What is still folded over the top edge of this donut trailer side?",correct:"Grey liner and tape flaps, so the panels are still hinged.",wrong:"Nothing. The side is trimmed and finished."} },
    /* 2.7.1 media add — Drive stills, reviewed frame-by-frame; appended so free first-14 stay free */
    { id:"pb-271-handle-recess", title:"Light-blue entry — handle recess tuck", image:"media/photos/gallery/light-blue-entry-handle-recess-tuck.jpg", module:"seams-rivets", jobType:"RV / Bus",
      visual:"Close-up of a paddle-style entry door handle and lock recess wrapped in light-blue film on a darker blue body panel. Two silver key cylinders show; film is trimmed to the black gasket edges.",
      narration:"Hardware recesses are where wraps look sloppy. Seat the film into the pocket, then knife the gasket lines. Do not bridge the paddle.",
      checklist:["Seat film into the recess","Knife the gasket edges","Do not bridge the paddle","Wipe dust before you call it done"],
      quiz:{q:"Handle recess. First move?",correct:"Seat the film into the pocket, then knife the gasket.",wrong:"Stretch film flat across the paddle so it stays glossy."} },
    { id:"pb-271-handle-keys", title:"Light-blue entry — key cylinders cut out", image:"media/photos/gallery/light-blue-entry-handle-key-cylinders.jpg", module:"seams-rivets", jobType:"RV / Bus",
      visual:"Same light-blue entry handle from a slightly tighter angle. Film wraps the recess frame; both key cylinders are cut out and show silver metal.",
      narration:"Cut cylinders out clean. Leave the black gasket as the stop. If the edge ticks up, lift, reclean, reseat.",
      checklist:["Cut cylinders clean","Stop at the gasket","Check for tick-up","Reseat if an edge lifts"],
      quiz:{q:"Key cylinder. Rule?",correct:"Cut it out clean and stop at the gasket.",wrong:"Wrap over the cylinder so the key still turns under film."} },
    { id:"pb-271-corner-seam", title:"Red over blue — corner seam at the light", image:"media/photos/gallery/red-blue-corner-seam-overlap-rivets.jpg", module:"seams-rivets", jobType:"Trailer",
      visual:"Vertical corner where glossy red film overlaps metallic blue film. Rivets show under the red. A red marker light sits at the bottom left.",
      narration:"Color changes at a corner need a deliberate overlap. Seat both faces, keep the edge straight, and do not stretch the red around the radius.",
      checklist:["Plan the overlap face","Seat both faces","Keep the edge straight","Do not stretch around the radius"],
      quiz:{q:"Two colors meet at a corner. Move?",correct:"Overlap on purpose and seat both faces.",wrong:"Butt the colors with no overlap so the seam disappears."} },
    { id:"pb-271-taillight", title:"Red taillight bezel — vertical seam below", image:"media/photos/gallery/red-taillight-bezel-vertical-seam.jpg", module:"seams-rivets", jobType:"Trailer",
      visual:"Stadium-shaped red LED taillight in a black bezel on glossy red film. A clean vertical seam runs down from the bottom center screw of the bezel.",
      narration:"Lights get a relief and a planned seam. Finish the bezel edge, then run the vertical joint straight down the panel.",
      checklist:["Relief around the bezel","Seat under the trim ring","Keep the vertical seam straight","Check screws are clear of film"],
      quiz:{q:"Seam under a taillight. Goal?",correct:"A straight vertical joint off the bezel.",wrong:"Stretch one panel under the whole light with no seam."} },
    { id:"pb-271-practice-wall", title:"Practice wall — color panels and brick film", image:"media/photos/gallery/practice-wall-color-and-brick-panels.jpg", module:"architectural", jobType:"Interior",
      visual:"Shop practice wall with five glossy solid color panels (purple, brown, maroon, magenta, red) next to red-brick and black-brick textured panels on a concrete floor.",
      narration:"This is a practice wall, not a vehicle. Use it to rehearse plumb hangs, texture reads, and outside corners before you bill a client wall.",
      checklist:["Hang plumb on solids","Read brick mortar lines","Practice the outside corner","Raking light before you stop"],
      quiz:{q:"What is this wall for?",correct:"Practice hangs, texture, and corners before a client job.",wrong:"A finished storefront that goes out the door as-is."} },
    { id:"pb-271-brick-corner", title:"Black brick film — outside corner", image:"media/photos/gallery/black-brick-film-outside-corner.jpg", module:"architectural", jobType:"Interior",
      visual:"L-shaped kiosk prop wrapped in glossy black brick-pattern film. Bright reflection runs the outside corner. Concrete floor and shop shelves behind.",
      narration:"Outside corners on textured film show every stretch. Keep mortar lines level around the turn and do not burnish the corner round.",
      checklist:["Keep mortar lines level","Seat both faces of the corner","Do not round-burnish the edge","Check the corner in raking light"],
      quiz:{q:"Brick film outside corner. Watch?",correct:"Mortar line level around the turn.",wrong:"Stretch the corner hard so the bricks disappear."} },
    { id:"pb-271-brick-mortar", title:"Black brick film — mortar close-up", image:"media/photos/gallery/black-brick-film-mortar-close.jpg", module:"architectural", jobType:"Interior",
      visual:"Tight close-up of black brick-pattern film with light grey mortar lines. Gloss highlights show on the brick faces.",
      narration:"Textured brick film has to sit in the mortar. If you only burnish the brick faces, the grooves tent and the pattern reads fake.",
      checklist:["Seat film into mortar grooves","Light strokes on brick faces","No dry burnish that mars gloss","Raking light to catch tents"],
      quiz:{q:"Brick film looks tented in the grooves. Cause?",correct:"Faces were burnished; mortar was never seated.",wrong:"The film needs more heat until the bricks melt flat."} },
    { id:"pb-271-grey-knife", title:"Grey film — knife at the door handle", image:"media/photos/gallery/grey-film-knife-at-door-handle.jpg", module:"squeegee", jobType:"Vehicles",
      visual:"Light grey glossy film across a horizontal door-handle recess. A white-handled snap-off knife tip sits at the right end of a horizontal slit in the film.",
      narration:"Handles get a controlled slit, then a trim to the housing. Do not plunge deep — score and finish on a second pass.",
      checklist:["Slit the handle opening controlled","Trim to the housing","Do not plunge deep","Wipe the cut edge"],
      quiz:{q:"First cut at a door handle?",correct:"A controlled slit, then trim to the housing.",wrong:"One deep plunge through film and paint."} },
    { id:"pb-271-grey-pinch", title:"Grey film — pinch in a body channel", image:"media/photos/gallery/grey-film-pinch-in-body-channel.jpg", module:"squeegee", jobType:"Vehicles",
      visual:"Light grey glossy film bridging a horizontal body channel. A pinch fold sits in the recess with finger wrinkles below. A sliver of rose paint shows at the right edge.",
      narration:"This is a tension mistake. The channel was bridged instead of fed. Lift, relieve, and reseat — do not smash the pinch flat.",
      checklist:["Recognize a bridge vs a seat","Lift and relieve the pinch","Feed film into the channel","Reseat without smashing the fold"],
      quiz:{q:"Pinch sitting in a channel. Move?",correct:"Lift, relieve, and feed film into the channel.",wrong:"Burnish the pinch flat so it disappears."} },
    { id:"pb-271-circle-hinge", title:"Red circle graphic — panel still hinged", image:"media/photos/gallery/red-circle-graphic-panel-hinge-stage.jpg", module:"squeegee", jobType:"Box truck",
      visual:"White trailer or box side mid-hang with red circle graphics. A large panel is peeled back showing 3M-branded white liner. Teal hinge tape and a silver A-frame ladder are in front of the panel.",
      narration:"Big printed panels stay hinged until registration is checked. The liner peel and tape strips are the hinge — do not pull them until the print lines up across the seam.",
      checklist:["Check print registration across the seam","Treat tape and liner as the hinge","Squeegee from the hinge out","Pull tape low and slow"],
      quiz:{q:"Why is the panel still peeled back?",correct:"It is hinged so registration can be checked.",wrong:"The job is finished and the liner is decorative."} },
    { id:"pb-271-rv-inlays", title:"RV rear — orange and yellow corner inlays", image:"media/photos/gallery/rv-rear-orange-yellow-corner-inlays.jpg", module:"seams-rivets", jobType:"RV / Bus",
      visual:"Rear corner of a white coach or RV. Dark upper graphic, vertical orange stripe with a yellow inner stripe, bright orange wrap around two round red taillights. Excess orange film hangs mid-job. Shop ladder in the background.",
      narration:"Rear corners on coaches are inlay work. Fit the color breaks to the lights and the radius before you chase heat. Follow the film TDS.",
      checklist:["Dry-fit the inlay to the lights","Seat the radius before heat","Trim lights after the hang","Follow the film TDS"],
      quiz:{q:"Coach rear corner inlays. First?",correct:"Dry-fit color breaks to lights and radius.",wrong:"Heat the whole corner and stretch one panel around."} },
    { id:"pb-271-blue-fender", title:"Blue fender mid-hang on yellow cab", image:"media/photos/gallery/blue-fender-mid-hang-yellow-cab.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Bright blue gloss film mid-hang over a rounded yellow fender. Film is smooth on the outer curve and bunched at the top and right. Tire arc at the bottom; black graphic lines on white above.",
      narration:"Fenders are glass-then-feed. Get the crown seated before you chase the wheel-lip. Wrinkles at the edge mean you still have feed left.",
      checklist:["Seat the crown first","Feed toward the wheel lip","Do not smash edge wrinkles early","Trim the lip last"],
      quiz:{q:"Fender mid-hang with edge wrinkles. Meaning?",correct:"Crown is set; you still have feed at the lip.",wrong:"The film is ruined and the panel must be scrapped."} }
  ];

  var have = {};
  for (var i = 0; i < d.photoLessons.length; i++) have[d.photoLessons[i].id] = 1;
  for (var j = 0; j < extra.length; j++) {
    if (!have[extra[j].id]) d.photoLessons.push(extra[j]);
  }
})();
