/* Extra photo lessons — only stills that exist in the repo. */
(function () {
  window.WRAP911_BOOST = 1;
  if (!window.WRAP911_DATA) window.WRAP911_DATA = {};
  var d = window.WRAP911_DATA;
  if (!d.photoLessons) d.photoLessons = [];

  var extra = [
    { id:"pb-caddy-3", title:"Pink caddy — side hang in the bay", image:"media/videos/fleet/pink-caddy-wrap3.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Dusty-rose Cadillac in the bay mid-wrap.",
      narration:"This is the fleet side hang. Glass the flats, watch the character line, do not chase heat numbers. TDS only.",
      checklist:["Glass the door flats first","Keep the character line level","Heat only to the film TDS","Walk the panel in raking light"],
      quiz:{q:"First move on a fleet side hang?",correct:"Glass the flats and read the character line.",wrong:"Torch the whole door before the film is placed."} },
    { id:"pb-caddy-4", title:"Pink caddy — bumper to fender seam", image:"media/videos/fleet/pink-caddy-wrap4.jpg", module:"seams-rivets", jobType:"Fleet",
      visual:"Seam at bumper-to-fender on the rose wrap.",
      narration:"Seams fail when you stretch across a gap. Overlap to the TDS, seat both faces, post-heat the join.",
      checklist:["Do not stretch across the gap","Overlap per TDS","Seat both faces","Post-heat the join"],
      quiz:{q:"How do you treat a bumper-to-fender seam?",correct:"Overlap per TDS and seat both faces.",wrong:"Pull one panel tight across the gap so there is no seam."} },
    { id:"pb-caddy-5", title:"Pink caddy — rear quarter finish", image:"media/videos/fleet/pink-caddy-wrap5.jpg", module:"post-heat", jobType:"Fleet",
      visual:"Rear quarter after the hang.",
      narration:"Finish is post-heat and edge check. If an edge ticks up, lift, reclean, reseat. Do not glue dirt in.",
      checklist:["Post-heat per TDS","Check wheel-well lips","Reseat any tick-up","Raking light before you call it done"],
      quiz:{q:"Edge ticked up after post-heat. Move?",correct:"Lift, reclean, reseat.",wrong:"Melt it down with a long torch hold."} },
    { id:"pb-caddy-1", title:"Pink wrap caddy — first hang", image:"media/videos/fleet/pink-wrap-caddy-1.jpg", module:"prep", jobType:"Fleet",
      visual:"First film on the caddy.",
      narration:"Prep decides this job. Clay or wipe per shop process, IPA, dry, then hang. Dirty paint becomes a lift line.",
      checklist:["Wash and decon","IPA, then dry","Hang only on a clean panel","Bag dirty towels"],
      quiz:{q:"When does film go on?",correct:"After the panel is clean and dry.",wrong:"As soon as the roll is on the floor."} },
    { id:"pb-cherokee", title:"Satin Cherokee — full-side read", image:"media/videos/fleet/satin-wrap-cherokee.jpg", module:"film-types", jobType:"Fleet",
      visual:"Satin SUV side in the bay.",
      narration:"Satin shows squeegee tracks and overstretch more than gloss. Light strokes. Do not burnish satin like gloss.",
      checklist:["Light squeegee pressure","Watch satin marring","No dry burnish","Read the side in raking light"],
      quiz:{q:"Why go light on satin?",correct:"Satin shows tracks and stretch marks that gloss hides.",wrong:"Satin needs more heat than gloss to look even."} },
    { id:"pb-graphic", title:"Printed graphic install", image:"media/videos/fleet/graphic-installation-1.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Printed graphic going down.",
      narration:"Printed film creases if you smash fingers. Lift, set tension, squeegee from glassed film out. Pattern stays level.",
      checklist:["Keep the print level","Lift fingers, do not smash","Squeegee from the glassed area out","Watch seams in the art"],
      quiz:{q:"Finger in printed film. Move?",correct:"Lift and reset tension. Do not smash it flat.",wrong:"Hard squeegee so the print compresses."} },
    { id:"pb-wall", title:"Interior wall wrap", image:"media/videos/architectural/architectural-wall-wrap.jpg", module:"architectural", jobType:"Interior",
      visual:"Wall panel in the shop.",
      narration:"Same film rules as a van. Layout first, hang plumb, squeegee in sequence. Heat only to TDS for fingers.",
      checklist:["Layout and plumb","Sequence the squeegee","Heat fingers to TDS","Trim off the show face"],
      quiz:{q:"What is first on an interior wall?",correct:"Layout and plumb, then hang.",wrong:"Heat the whole wall so the film gets soft."} },
    { id:"pb-wall-sq", title:"Wall squeegee sequence", image:"media/videos/architectural/architectural-wall-wrap-squeegee-sequence.jpg", module:"squeegee", jobType:"Interior",
      visual:"Squeegee pattern on a wall panel.",
      narration:"Sequence beats force. Overlap strokes. Do not leave a dry island in the middle of the panel.",
      checklist:["Overlap strokes","No dry islands","Soft edge on texture","Check raking light"],
      quiz:{q:"Squeegee rule on a wall?",correct:"Overlapped sequence. No dry islands.",wrong:"One hard pass down the center."} },
    { id:"pb-cut-ex1", title:"Cut excess after the wall is down", image:"media/videos/architectural/architectural-panel-cutting-excess-vinyl-after-install-1.jpg", module:"cutting", jobType:"Interior",
      visual:"Trimming excess after install.",
      narration:"Finish cuts use a fresh blade and light pressure. Film only. Do not score the wall.",
      checklist:["Fresh blade","Light pass","Film only","Bag the scrap"],
      quiz:{q:"Finish trim pressure?",correct:"Light. Film only. Fresh blade.",wrong:"Lean on the knife so it does not skip."} },
    { id:"pb-cab-done", title:"Cabinet wrap — faces done", image:"media/videos/architectural/cabinet-done.jpg", module:"architectural", jobType:"Interior",
      visual:"Finished cabinet faces.",
      narration:"Cabinet jobs die at edges and inside corners. Half-moon relief, seat one face, then the other.",
      checklist:["Measure twice","Relief inside corners","Seat one face at a time","No bridging of the door gap"],
      quiz:{q:"Inside cabinet corner. Cut?",correct:"Half-moon relief, then one face at a time.",wrong:"One panel stretched around the box."} },
    { id:"pb-cab-on", title:"Vinyl on cabinet", image:"media/videos/architectural/vinyl-oncabinet8.jpg", module:"architectural", jobType:"Interior",
      visual:"Film on a cabinet box.",
      narration:"Hinge side last. Do not wrap the hinge barrel unless the spec says so. Clean the edge after trim.",
      checklist:["Hinge side last","Do not wrap the barrel unless specked","Clean the cut edge","Check door close"],
      quiz:{q:"When do you wrap the hinge side?",correct:"Last, and only as far as the spec.",wrong:"First, so the door can close on fresh film."} },
    { id:"pb-office", title:"Office wall finish", image:"media/photos/gallery/office-wallpaper-wrap.jpg", module:"architectural", jobType:"Interior",
      visual:"Conference wall wrap.",
      narration:"Architectural film still needs prep. Dust on a wall becomes a tent you will see under lights.",
      checklist:["Dust the wall","Layout seams off sight lines","Squeegee sequence","Raking light at the end"],
      quiz:{q:"Main enemy on an office wall?",correct:"Dust and a seam in the sight line.",wrong:"Not enough torch heat on the field."} },
    { id:"pb-bleed", title:"Measure bleed on wood-grain", image:"media/photos/gallery/measuring-bleed2.jpg", module:"cutting", jobType:"Interior",
      visual:"Measuring bleed on wood-grain film.",
      narration:"Bleed is planned. Cut short and the core shows. Leave wrap allowance, then finish-trim.",
      checklist:["Measure the box","Add bleed","Cut long, trim after hang","Match grain direction"],
      quiz:{q:"Why add bleed?",correct:"So the finish trim does not show the substrate.",wrong:"So you can stretch the grain farther."} },
    { id:"pb-cab-side", title:"Cabinet interior side", image:"media/photos/gallery/cabinet-pic-sides.jpg", module:"architectural", jobType:"Interior",
      visual:"Cabinet interior side and glass corner.",
      narration:"Interior sides are tight. Dry-fit, hinge clearance, then hang. Do not bridge the glass channel.",
      checklist:["Dry-fit the piece","Watch hinge clearance","No bridge on glass channel","Soft squeegee"],
      quiz:{q:"Glass channel next to film. Move?",correct:"Trim to the channel. Do not bridge it.",wrong:"Stretch film over the glass so it looks sealed."} },
    { id:"pb-cab-measure", title:"Cabinet measure before the cut", image:"media/photos/gallery/cabinet-measure.jpg", module:"prep", jobType:"Interior",
      visual:"Measuring cabinet box height.",
      narration:"The cut is only as good as the measure. Height, width, depth, then bleed. Write it on the liner.",
      checklist:["Height, width, depth","Add bleed","Write sizes on the liner","Cut once"],
      quiz:{q:"What do you write on the liner?",correct:"The measured size plus bleed.",wrong:"Only the brand name."} },
    { id:"pb-kiosk", title:"Kiosk box — multi-panel face", image:"media/photos/gallery/kiosk-box.jpg", module:"architectural", jobType:"Interior",
      visual:"Kiosk with cutouts.",
      narration:"Cutouts first in the layout. Relief around openings. Do not stretch art across a hole.",
      checklist:["Mark every cutout","Relief around openings","Keep art square","Trim after the face is glassed"],
      quiz:{q:"Printed kiosk with a hole. Rule?",correct:"Layout the hole first. Do not stretch art across it.",wrong:"Stretch the print over the hole and cut later."} },
    { id:"pb-spot", title:"Trailer spot graphic at the hinge", image:"media/photos/gallery/trailer-spot-graphics.jpg", module:"post-heat", jobType:"Trailer",
      visual:"Spot graphic under tape at a hinge.",
      narration:"Tape off low and slow. Trim the hinge after the tape is gone.",
      checklist:["Squeegee tape down","Pull 180 degrees","Stop if a corner lifts","Trim hinge last"],
      quiz:{q:"When do you trim the hinge?",correct:"After the transfer tape is off.",wrong:"Before you pull tape, so the hinge is free."} },
    { id:"pb-gate", title:"Work van — rear gate wrap", image:"media/videos/van/rear-vehicle-gate-wrap.jpg", module:"squeegee", jobType:"Work van",
      visual:"Rear gate mid-wrap.",
      narration:"Gates have recesses and badges. Glass the flat, relief the handle, do not bridge the latch pocket.",
      checklist:["Glass the gate flat","Relief the handle","No bridge on the latch","Check the close"],
      quiz:{q:"Latch pocket. Move?",correct:"Relief and feed. Do not bridge.",wrong:"Stretch film over the latch so it stays glossy."} },
    { id:"pb-squeegee", title:"Squeegee strokes on the table", image:"media/videos/prep/squeegee-strokes.jpg", module:"squeegee", jobType:"Fleet",
      visual:"Squeegee work on film.",
      narration:"Stroke pattern on the table is the same on the vehicle. Overlap. Soft edge. No dry islands.",
      checklist:["Overlap","Soft edge","No dry islands","Wipe the squeegee face"],
      quiz:{q:"Why wipe the squeegee?",correct:"Grit on the blade scratches film.",wrong:"So the heat transfers better."} },
    { id:"pb-torch", title:"Heat on vinyl — keep it moving", image:"media/videos/prep/torch-on-vinyl1.jpg", module:"heat", jobType:"Fleet",
      visual:"Torch over film.",
      narration:"Heat is a tool. Keep it moving. TDS only. If the film goes shiny-melted you went past the window.",
      checklist:["Keep the heat moving","TDS only","Stop when pliable","Never hold on one spot"],
      quiz:{q:"Film looks shiny-melted. Meaning?",correct:"You passed the TDS window. Stop.",wrong:"It is ready for a harder squeegee."} },
    { id:"pb-removal", title:"Vinyl removal", image:"media/videos/prep/vinyl-removal.jpg", module:"prep", jobType:"Fleet",
      visual:"Old film coming off.",
      narration:"Removal is heat and a low pull. Adhesive left behind gets removed with the product the TDS names. Do not invent a soup.",
      checklist:["Heat to release","Low pull","Adhesive remover per TDS","Prep again before the new hang"],
      quiz:{q:"What remover do you use?",correct:"The one named in the film TDS.",wrong:"Whatever solvent is under the bench."} }
  ];

  var have = {};
  for (var i = 0; i < d.photoLessons.length; i++) have[d.photoLessons[i].id] = 1;
  for (var j = 0; j < extra.length; j++) {
    if (!have[extra[j].id]) d.photoLessons.push(extra[j]);
  }
})();
